src/main/urls.py
from django.urls import path, include
from .views import HomepageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('gradesystem/', HomepageView.as_view(template_name='main/gradesystem.html'), name='gradesystem'),
    path('programs/', HomepageView.as_view(template_name='main/programs.html'), name='programs'),
    path('rules/', HomepageView.as_view(template_name='main/rules.html'), name='rules'),
    path('placementProcedure/', HomepageView.as_view(template_name='main/placementprocedure.html'),
         name='placementProcedure'),
    path('contacts/', HomepageView.as_view(template_name='main/contacts.html'), name='contacts'),
    path('admissions/', HomepageView.as_view(template_name='main/admissions.html'), name='admissions'),
    path('achievements/', HomepageView.as_view(template_name='main/achievements.html'), name='achievements'),
    path('profile/', HomepageView.as_view(template_name='main/prospective.html'), name='profile'),
    path('alumni/', HomepageView.as_view(template_name='main/alumni.html'), name='alumni'),
    path('student_rules/', HomepageView.as_view(template_name='main/student_rules.html'), name='student_rules'),
    path('internships/', HomepageView.as_view(template_name='main/internships.html'), name='internships'),
    path('why_recruit/', HomepageView.as_view(template_name='main/why-recruit.html'), name='why-recruit'),
    path('brochure/', HomepageView.as_view(template_name='main/brochure.html'), name='brochure'),
    path('summary/', HomepageView.as_view(template_name='main/summary.html'), name='summary'),
    path('company_rules/', HomepageView.as_view(template_name='main/company_rules.html'), name='company_rules'),
    path('past_recruiters/', HomepageView.as_view(template_name='main/past_recruiters.html'), name='past_recruiters'),
    path('aipc/', HomepageView.as_view(template_name='main/aipc.html'), name='aipc'),
    path('jaf/', HomepageView.as_view(template_name='main/jaf.html'), name='jaf'),
    path('iaf/', HomepageView.as_view(template_name='main/iaf.html'), name='iaf'),
    path('reachus/', HomepageView.as_view(template_name='main/reachus.html'), name='reachus'),
    path('invitation/', HomepageView.as_view(template_name='main/invitation.html'), name='invitation'),
    path('dir_msg/', HomepageView.as_view(template_name='main/dir_msg.html'), name='dir_msg'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('chairman_msg/', HomepageView.as_view(template_name='main/chairman_msg.html'), name='chairman_msg'),
]

src/spc_django/urls.py
from django.urls import path, include
from django.contrib import admin
from accounts.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView

admin.site.site_title = 'SPC Administration'
admin.site.site_header = 'SPC Administration'
admin.site.index_title = 'Admin Panel'

urlpatterns = [
                  path('login/', LoginView.as_view(), name='login'),
                  path('logout/', LogoutView.as_view(), name='logout'),
                  path('admin/', admin.site.urls),
                  path('company/', include('company.urls')),
                  path('student/', include('student.urls')),
                  path('', include('main.urls')),
                  path('password_reset/',
                       PasswordResetView.as_view(email_template_name='accounts/password_reset_email.html',
                                                 subject_template_name='accounts/password_reset_subject.txt'),
                       name='password_reset'),
                  path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
                  path('reset/<uidb64>[0-9A-Za-z_-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
                       auth_views.password_reset_confirm, name='password_reset_confirm'),
                  path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class HomeImageCarousel(models.Model):
    image_no = models.PositiveIntegerField(default=64)
    image_title = models.CharField(default="image", max_length=64)
    image_carousel = models.ImageField(upload_to='', blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.image_title

     #def save_post(self):
      #   self.save()

src/main/models.py
from django.db import models
from django.contrib.auth.models import User
from student.models import ProgramAndBranch
import re


class News(models.Model):
    title = models.CharField(max_length=64, blank=True)
    order_no = models.PositiveSmallIntegerField(default=512)
    content = models.TextField(max_length=512)
    active = models.BooleanField(default=True)
    document = models.FileField(upload_to='news', blank=True, null=True)
    file_title = models.CharField(max_length=64, default='Read More')
    link = models.URLField(blank=True, null=True)
    link_title = models.CharField(max_length=64, default='Link')

    def __str__(self):
        return self.title


class PastRecruiters(models.Model):
    company_order_no = models.PositiveIntegerField(default=64)
    company_name = models.CharField(max_length=64)
    company_logo = models.ImageField(upload_to='company-logo', blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.company_name

class HomeImageCarousel(models.Model):
    ordering = models.PositiveIntegerField(default=64)
    title = models.CharField(max_length=64)
    image = models.ImageField(upload_to='homepage-carousel', blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class CoreTeamContacts(models.Model):
    DESIGNATION_CHOICES = (
        ('1', 'Chairman'),
        ('2', 'Placement Officer'),
        ('3', 'Project Superintendent'),
        ('4', 'Student Co-ordinator'),
        ('5', 'Department Representative'),
        ('6', 'Team Member'),
        ('7', 'Web Development Team'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=64, choices=DESIGNATION_CHOICES)
    sub_designation = models.CharField(max_length=64, default='Office of Student Placement')
    program_branch = models.ForeignKey(ProgramAndBranch, on_delete=models.SET_NULL, null=True)
    phone = models.CharField(max_length=16, blank=True, null=True)
    github_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='contacts', blank=True, null=True)
    active = models.BooleanField(default=True)
    order_no = models.PositiveIntegerField(default=64)

    def get_github_username(self):
        x = re.split("https://github.com/", str(self.github_link))
        return x[1]

    def get_linkedin_username(self):
        x = re.split("https://www.linkedin.com/in/", str(self.linkedin_link))
        return x[1]

    def __str__(self):
        return self.user.get_full_name()


class Volunteers(models.Model):
    YEAR_CHOICES = (
        ('1', 'Sophmore Year'),
        ('2', 'Postgraduation'),
    )

    name = models.CharField(max_length=64)
    year = models.CharField(max_length=64, choices=YEAR_CHOICES, null=True)
    program_branch = models.ForeignKey(ProgramAndBranch, on_delete=models.SET_NULL, null=True, blank=True)
    active = models.BooleanField(default=True)
    order_no = models.PositiveIntegerField(default=64)

    def __str__(self):
        return self.name


class AlumniTestimonial(models.Model):
    alumni_name = models.CharField(max_length=64)
    company_working = models.CharField(max_length=64)
    designation = models.CharField(max_length=64, null=True)
    testimonial = models.TextField(null=False)
    alumni_image = models.ImageField(upload_to='alumni-testimonial')
    active = models.BooleanField(default=True)
    ranking = models.PositiveSmallIntegerField(default=512)

    def __str__(self):
        return self.alumni_name

main/views.py
from django.views.generic import TemplateView
import os
from .models import HomeImageCarousel


class HomepageView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data()
        carousel = os.listdir("media")
        print(carousel)
        carousel.sort(key=lambda x: os.path.getmtime('media/' + x), reverse=True)
        print(carousel)
        carousel = ['/' + image for image in carousel]
        context['carousel'] = carousel
        context['carousel'] = HomeImageCarousel.objects.filter(active=True).order_by('image_no') 
        companies = os.listdir("staticfiles/img/company-logo")
        companies = ['img/company-logo/' + image for image in companies]
        context['companies'] = companies
        return context

    

src/main/views.py
from django.views.generic import TemplateView
import os
from .models import News, PastRecruiters, HomeImageCarousel


class HomepageView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data()
        context['carousel'] = HomeImageCarousel.objects.filter(active=True).order_by('ordering')
        context['news_list'] = News.objects.filter(active=True).order_by('order_no')
        context['companies'] = PastRecruiters.objects.filter(active=True).order_by('company_order_no')
        context['contacts'] = CoreTeamContacts.objects.filter(active=True).order_by('order_no')
        context['volunteers'] = Volunteers.objects.filter(active=True).order_by('order_no')
        context['testimonial_list'] = AlumniTestimonial.objects.filter(active='True').order_by('ranking')
        return context

templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    {% block header %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/style.css' %} " rel="stylesheet">
    <link rel="icon" href="{% static 'img/iitj.png' %}">

    <title>Office of Student Placements, IIT Jodhpur</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    {% endblock %}
</head>
<body>
<!---
    <div class="main-heading">
        <div class="row">
            <div class="col-md-12">
                <div class="media">
                    <a class="thumbnail pull-left">
                        &nbsp &nbsp
                        <img src="{% static '/img/logo2.png' %}" alt="IIT Jodhpur" class="logo">
                    </a>
                    <div class="media-body pt-1 pl-3">
                        <div class="pull-right py-1">
                            <div class="login-block">
                                <a class="my-auto" href="{% url 'login' %}">Recruiter Login</a>
                            </div>
                            <div class="login-block">
                                <a class="my-auto" href="{% url 'login' %}">Student Login</a>
                            </div>
                        </div>
                        <h2 class="heading">
                            <a href="http://spc.iitj.ac.in/">
                                Office of Student Placements
                            </a>
                        </h2>
                        <h4 class="heading">Indian Institute of Technology Jodhpur</h4>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
    --->
    {% block navbar %}

    <nav class="navbar navbar-expand-lg navbar-toggleable-md navbar-dark sticky-top">
        <div class="container-fluid" style="width: 100%">
            <div class="row">
             <div class="col-md-12">
                <div class="media">
                    <a class="navbar-brand">

                        <img src="{% static '/img/logo.gif' %}" alt="IIT Jodhpur" class="logo">
                    </a>

                    <div class="media-body pt-1 pl-3">
                        <div class="pull-right py-1">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapseEx12"
                    aria-controls="collapseEx12" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="collapseEx12">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item btn-group hoverable">
                        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Home</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'main:home' %}">About Us</a>
                            <a class="dropdown-item" href="{% url 'main:invitation' %}">Invitation</a>
                            <a class="dropdown-item" href="{% url 'main:chairman_msg' %}">Chairman's Message</a>
                            <a class="dropdown-item" href="{% url 'main:dir_msg' %}">Director's Message</a>
                        </div>
                    </li>
                    <li class="nav-item btn-group hoverable">
                        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Academics</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'main:gradesystem' %}">Gradesystem</a>
                            <a class="dropdown-item" href="{% url 'main:programs' %}">Programmes</a>
                            <a class="dropdown-item" href="{% url 'main:admissions' %}">Admission Procedure</a>
                        </div>
                    </li>
                    <li class="nav-item btn-group hoverable">
                        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Students</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'main:achievements' %}">Achievements</a>
                            <a class="dropdown-item" href="{% url 'main:profile' %}">Prospective</a>
                            <!-- <a class="dropdown-item" href="{% url 'main:alumni' %}">Alumni's Words</a> -->
                            <a class="dropdown-item" href="{% url 'main:student_rules' %}">Norms/Guidelines</a>
                            <a class="dropdown-item" href="{% url 'main:internships' %}">Internships</a>
                        </div>
                    </li>
                    <li class="nav-item btn-group hoverable">
                        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Recruiter</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'main:why-recruit' %}">Why Recruit?</a>
                            <a class="dropdown-item" href="{% url 'main:brochure' %}">Brochure</a>
                            <a class="dropdown-item" href="{% url 'main:summary' %}">Summary</a>
                            <a class="dropdown-item" href="{% url 'main:placementProcedure' %}">Placement Procedure</a>
                            <a class="dropdown-item" href="{% url 'main:company_rules' %}">Norms/Guidelines</a>
                            <a class="dropdown-item" href="{% url 'main:past_recruiters' %}">Past Recruiters</a>
                            <a class="dropdown-item" href="{% url 'main:aipc' %}">AIPC Norms</a>
                        </div>
                    </li>
                    <li class="nav-item btn-group hoverable">
                        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Forms</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'main:jaf' %}">JAF</a>
                            <a class="dropdown-item" href="{% url 'main:iaf' %}">IAF</a>

                        </div>
                    </li>
                    <li class="nav-item btn-group hoverable">
                        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Contact Us</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'main:contacts' %}">Contacts</a>
                            <a class="dropdown-item" href="{% url 'main:reachus' %}">Reach Us</a>
                        </div>
                    </li>
                    <li class="nav-item btn-group hoverable">
                        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Login</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="{% url 'login' %}">Recruiter Login</a>
                            <a class="dropdown-item" href="{% url 'login' %}">Student Login</a>
                        </div>
                    </li>

                </ul>

            </div>
                        </div>
                        <h2 class="heading">
                            <a href="http://spc.iitj.ac.in/">
                                Office of Student Placements
                            </a>
                        </h2>
                        <h4 class="heading" style="color: white">Indian Institute of Technology Jodhpur</h4>

                    </div>
                </div>
            </div>

            </div>
         </div>

    </nav>
    <br>

<!--
    <div class="row">
        {% if not 'register' in request.path and not 'contacts' in request.path %}
        <div class="col-lg-2" id="past_recruiters">

            <center><h3>Past Recruiters</h3></center>
            <br>
            <marquee BEHAVIOR="alternate" direction="up" HEIGHT=600 scrollamount="4" onmouseover="this.stop();"
                     onmouseout="this.start();">
                {% for company in companies %}
                <br>
                <img class="d-block w-100" src="{% static company %}">
                {% endfor %}
                <br>
            </marquee>
        </div>
        {% endif %}--->


        {% endblock %}
        {% block body %}

        {% endblock %}

    </div>

    {% block footer %}
    <br>
    <footer class="footer-basic-centered">
        <p class="footer-logos">
            <a href="https://www.facebook.com/SPC.IITJ/" target="_blank">
                <i style="color: white" class="fa fa-facebook"></i>
            </a>
            <a href="https://www.linkedin.com/in/office-of-student-placements-iit-jodhpur-62a31352/" target="_blank">
                <i style="color: white" class="fa fa-linkedin"></i>
            </a>
            <a href="https://github.com/anshulahuja98/spc_portal" target="_blank">
                <i style="color: white" class="fa fa-github"></i>
            </a>
        </p>
        <p class="footer-company-name">Designed & Maintained by Office of Student Placements, IIT Jodhpur</p>

    </footer>
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static '/js/tether.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static '/js/mdb.min.js' %}"></script>

    {% endblock %}
</div>
</div>
</body>
</html>

templates/main/summary.html
{% extends 'main/base.html' %}
{% block body %}
<div class="row">
    <div class="col-lg-2">
                    {% include 'main/mixins/recruiters_mixin.html' with companies=companies %}

    </div>
    <div class="col-lg-10">
        <div class="card">
            <div class="my-card" id="my-card"><span style="font-size: 1.5rem"> &nbsp; Summary</span></div>
            <div class="card-block">
                <p class="card-text" style="text-align:justify;">
                    <!--This year, the placement season begin in the month of October 2017, total of <b>104 students registered for placements out of which 78 students got placed</b>. Most of the big corporates like Microsoft, Goldman Sachs, DE Shaw, Amazon, Morgan Stanley, Mahindra, Volvo Eicher, TVS, Tata Motors visited during this season. Some other placement trends are being mentioned below:<br>
                    --><ul class="a">
                        <li><a>For Placement Season 2018, 75% and 72% of B.Tech. and M.Tech. obtained job offers as compared to 72% and 37% in the academic year 2017.</a></li>
                        <li> There has been increase in the number of PPO’s offered to the companies. There are approximately 20 PPO’s offered from the companies.</li>
                        <li> Average salary over all the branches had been increased to 11 Lakhs.</li>
                        <li> This year, we have 45 recruiters who visited our campus</li>
                        <li> The branch wise placement statistics is mentioned below:</li>
                    </ul>
                </p>
                <br>
                    <div class="row">
                        <div class="col-lg-5">
                             <b style="font-size: large;">B.TECH PLACEMENTS :</b><br><br>
                            <table class="table table-bordered table-striped" style="width:auto;white-space: nowrap;">
                                <tr><th colspan="3" style="width:auto; text-align: center">PLACEMENT %</th></tr>
                                <tr><th style="width:auto;">Branch</th><th style="width:auto;">2017-2018</th><th style="width:auto;">2018-2019</th></tr>
                                <tr><td>Computer Science Engineering</td><td>91.7%</td><td>90%</td></tr>
                                <tr><td>Electrical Engineering</td><td>61%</td><td>78%</td></tr>
                                <tr><td>Mechanical Engineering</td><td>72%</td><td>70%</td></tr>
                                <tr><td>System Science</td><td>71%</td><td>NA</td></tr>
                                <tr><td>BISS</td><td>80%</td><td>NA</td></tr>
                                <tr><td><b>Overall </b></td><td>75.96%</td><td>80%</td></tr>
                            </table>
                        </div>
                        <div class="col-lg-5">
                             <b style="font-size: large"> </b><br><br>
                            <table class="table table-bordered table-striped" style="width:auto;white-space: nowrap;">
                                <tr><th colspan="3" style="width:auto; text-align: center">AVERAGE SALARY</th></tr>
                                <tr><th style="width:auto;">Branch</th><th style="width:auto;">2017-2018</th><th style="width:auto;">2018-2019</th></tr>
                                <tr><td>Computer Science Engineering</td><td>15.82 Lakhs</td><td>20.40 Lakhs</td></tr>
                                <tr><td>Electrical Engineering</td><td>8.96 Lakhs</td><td>10.39 Lakhs</td></tr>
                                <tr><td>Mechanical Engineering</td><td>6.62 Lakhs</td><td>8.09 Lakhs</td></tr>
                                <tr><td>System Science</td><td>16.44 Lakhs</td><td>NA</td></tr>
                                <tr><td>BISS</td><td>9.44 Lakhs</td><td>NA</td></tr>
                                <tr><td><b>Overall Average Salary </b></td><td>11.77 Lakhs</td><td>14.57 Lakhs</td></tr>
                                <tr><td><b>Median Salary </b></td><td>9.25 Lakhs</td><td>9.74 Lakhs</td></tr>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-5" >
                            <b>M.TECH PLACEMENTS :</b><br><br>
                            <table class="table table-bordered table-striped" style="width:auto;white-space: nowrap;">
                                <tr><th style="width:auto;">M.Tech</th><th style="width:auto;">2017-2018</th><th style="width:auto;">2018-2019</th></tr>
                                <tr><td>Placement %</td><td>75%</td><td>35%</td></tr>
                                <tr><td>Average Salary</td><td>6.5 Lakhs</td><td>7.25 Lakhs</td></tr>
                                <tr><td>Median Salary</td><td>5.75 Lakhs</td><td>6.25 Lakhs</td></tr>
                            </table>
                        </div>
                    </div>

            </div>
        </div>

            </div>
    <div class="col-lg-1">
    </div>
</div>
{% endblock %}