src/company/urls.py
from django.urls import path
from .views import InternshipAdvertisementFormView, JobAdvertisementFormView, InternshipAdvertisementAddedListView, \
    JobAdvertisementsAddedListView, \
    InternshipOfferView, JobOfferView
from accounts.views import CompanyRegisterFormView

app_name = 'company'

urlpatterns = [
    path('intern_offers/', InternshipAdvertisementAddedListView.as_view(), name='intern-offers-added'),
    path('job_offers/', JobAdvertisementsAddedListView.as_view(), name='job-offers-added'),
    path('joboffer_form/', JobAdvertisementFormView.as_view(), name="job-offer-form"),
    path('internoffer_form/', InternshipAdvertisementFormView.as_view(), name="intern-offer-form"),
    path('internship_offer/<uuid:id>/', InternshipOfferView.as_view(), name="internship-offer"),
    path('job_offer/<uuid:id>/', JobOfferView.as_view(), name="job-offer"),
    path('register/', CompanyRegisterFormView.as_view(), name='register'),

]

src/main/urls.py
from django.urls import path, include
from .views import HomepageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('gradesystem/', HomepageView.as_view(template_name='main/gradesystem.html'), name='gradesystem'),
    path('programs/', HomepageView.as_view(template_name='main/programs.html'), name='programs'),
    path('rules/', HomepageView.as_view(template_name='main/rules.html'), name='rules'),
    path('placementProcedure/', HomepageView.as_view(template_name='main/placementprocedure.html'),
         name='placementProcedure'),
    path('contacts/', HomepageView.as_view(template_name='main/contacts.html'), name='contacts'),
    path('admissions/', HomepageView.as_view(template_name='main/admissions.html'), name='admissions'),
    path('achievements/', HomepageView.as_view(template_name='main/achievements.html'), name='achievements'),
    path('profile/', HomepageView.as_view(template_name='main/prospective.html'), name='profile'),
    path('alumni/', HomepageView.as_view(template_name='main/alumni.html'), name='alumni'),
    path('student_rules/', HomepageView.as_view(template_name='main/student_rules.html'), name='student_rules'),
    path('internships/', HomepageView.as_view(template_name='main/internships.html'), name='internships'),
    path('why_recruit/', HomepageView.as_view(template_name='main/why-recruit.html'), name='why-recruit'),
    path('brochure/', HomepageView.as_view(template_name='main/brochure.html'), name='brochure'),
    path('summary/', HomepageView.as_view(template_name='main/summary.html'), name='summary'),
    path('company_rules/', HomepageView.as_view(template_name='main/company_rules.html'), name='company_rules'),
    path('past_recruiters/', HomepageView.as_view(template_name='main/past_recruiters.html'), name='past_recruiters'),
    path('aipc/', HomepageView.as_view(template_name='main/aipc.html'), name='aipc'),
    path('jaf/', HomepageView.as_view(template_name='main/jaf.html'), name='jaf'),
    path('iaf/', HomepageView.as_view(template_name='main/iaf.html'), name='iaf'),
    path('reachus/', HomepageView.as_view(template_name='main/reachus.html'), name='reachus'),
    path('invitation/', HomepageView.as_view(template_name='main/invitation.html'), name='invitation'),
    path('dir_msg/', HomepageView.as_view(template_name='main/dir_msg.html'), name='dir_msg'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('chairman_msg/', HomepageView.as_view(template_name='main/chairman_msg.html'), name='chairman_msg'),
]

src/spc_django/urls.py
from django.urls import path, include
from django.contrib import admin
from accounts.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView

admin.site.site_title = 'SPC Administration'
admin.site.site_header = 'SPC Administration'
admin.site.index_title = 'Admin Panel'

urlpatterns = [
                  path('login/', LoginView.as_view(), name='login'),
                  path('logout/', LogoutView.as_view(), name='logout'),
                  path('admin/', admin.site.urls),
                  path('company/', include('company.urls')),
                  path('student/', include('student.urls')),
                  path('', include('main.urls')),
                  path('password_reset/',
                       PasswordResetView.as_view(email_template_name='accounts/password_reset_email.html',
                                                 subject_template_name='accounts/password_reset_subject.txt'),
                       name='password_reset'),
                  path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
                  path('reset/<uidb64>[0-9A-Za-z_-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
                       auth_views.password_reset_confirm, name='password_reset_confirm'),
                  path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/company/models.py
from django.db import models
from uuid import uuid4
from django.shortcuts import reverse
from accounts.models import CompanyProfile, StudentProfile, Resume
from student.models import ProgramAndBranch
from django.db.models.signals import pre_save


class BaseAdvertisement(models.Model):
    # validity
    expiry = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=False)
    # job prof
    id = models.UUIDField(primary_key=True, default=uuid4)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
    designation = models.CharField(max_length=250)
    description = models.TextField()
    tentative_join_date = models.DateField()
    tentative_job_location = models.CharField(max_length=50)
    ads = models.FileField(upload_to='ads', null=True, blank=True)
    # package details
    ctc = models.FloatField()
    gross_salary = models.FloatField(null=True, blank=True)
    bonus = models.CharField(blank=True, null=True, max_length=100)
    bond = models.BooleanField()
    bond_details = models.TextField(blank=True, null=True)
    # selection process
    eligible_program_branch = models.ManyToManyField(ProgramAndBranch, default=ProgramAndBranch.objects.all())
    resume_required = models.BooleanField()
    resume_shortlist_criteria = models.TextField(null=True, blank=True)
    aptitude_test_required = models.BooleanField()
    group_discussion_required = models.BooleanField()
    number_of_technical_interviews = models.PositiveSmallIntegerField(default=0)
    number_of_technical_tests = models.PositiveSmallIntegerField(default=0)
    number_of_hr_rounds = models.PositiveSmallIntegerField(default=0)
    medical_test_required = models.BooleanField()
    min_gpa = models.FloatField()
    number_of_members = models.PositiveIntegerField(null=True, blank=True)
    other_details = models.TextField(null=True, blank=True)
    creation_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return "{} ({})".format(self.designation, self.company.name)


class JobAdvertisement(BaseAdvertisement):
    pass

    def get_absolute_url(self):
        return reverse("company:job-offer", kwargs={"id": self.id})

    def get_offers(self):
        return JobOffer.objects.filter(profile__id=self.id)


class InternshipAdvertisement(BaseAdvertisement):
    pass

    def get_absolute_url(self):
        return reverse("company:internship-offer", kwargs={"id": self.id})

    def get_offers(self):
        return InternshipOffer.objects.filter(profile__id=self.id)


class BaseOffer(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE, null=True)
    company = models.ForeignKey(CompanyProfile, on_delete=models.SET_NULL, null=True)
    is_accepted = models.BooleanField(default=False)
    ppo = models.BooleanField(default=False)
    resume = models.ForeignKey(Resume, on_delete=models.SET_NULL, null=True)
    application_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    @property
    def ctc(self):
        return self.profile.ctc

    def __str__(self):
        return "{} ({}) - {}".format(self.student.user.username, self.profile.designation,
                                     self.company.name)

    class Meta:
        abstract = True

    def get_file(self):
        if self.resume and self.resume.file:
            return self.resume.file
        else:
            return 'None'


class JobOffer(BaseOffer):
    profile = models.ForeignKey(JobAdvertisement, on_delete=models.CASCADE)


class InternshipOffer(BaseOffer):
    profile = models.ForeignKey(InternshipAdvertisement, on_delete=models.CASCADE)


def event_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.company:
        instance.company = instance.profile.company
    if instance.ppo and not instance.is_accepted:
        instance.is_accepted = True


pre_save.connect(event_pre_save_receiver, sender=InternshipOffer)

pre_save.connect(event_pre_save_receiver, sender=JobOffer)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Resume
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from .models import CompanyProfile, StudentProfile
from student.models import ProgramAndBranch


class ResumeForm(forms.ModelForm):
    file = forms.FileField()

    class Meta:
        model = Resume
        fields = ('file', 'reference', 'student')


class StudentRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Enter the same password as before, for verification.',
    )
    username = forms.CharField(max_length=11, help_text="Enter your Roll number, this will be used to login")
    year = forms.IntegerField(max_value=10, help_text="Enter value between 1-5, the current year of your degree")
    #program_branch = forms.ModelChoiceField(queryset=ProgramAndBranch.objects.all())
    gpa = forms.FloatField(max_value=10.00)
    ug_gpa = forms.FloatField(max_value=10.00, required=False)
    phone = forms.CharField(max_length=15)
    dob = forms.DateField()
    category = forms.ChoiceField(choices=StudentProfile.CATEGORY)
    jee_air = forms.IntegerField(required=False)
    physical_disability = forms.BooleanField(required=False)
    nationality = forms.ChoiceField(choices=StudentProfile.NATION)
    permanent_address = forms.CharField(widget=forms.Textarea)
    current_address = forms.CharField(widget=forms.Textarea)
    x_year = forms.IntegerField(max_value=2050, min_value=1980)
    x_board_name = forms.CharField(max_length=100)
    x_percentage = forms.CharField(max_length=10)
    xii_year = forms.IntegerField(max_value=2050, min_value=1980)
    xii_board_name = forms.CharField(max_length=100)
    xii_percentage = forms.CharField(max_length=16)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email']


class CompanyRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Enter the same password as before, for verification.',
    )
    username = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'maxlength': '254'}),
        help_text="This Email ID will be your username")
    name = forms.CharField(max_length=50, help_text="Name of the company")
    domain = forms.CharField(max_length=15, help_text="Type of company like banking/consulting etc ", required=False)
    url = forms.CharField(required=False)
    city = forms.CharField(max_length=15, required=False)
    state = forms.CharField(max_length=15, required=False)
    country = forms.ChoiceField(choices=CompanyProfile.NATION)
    pin_code = forms.CharField(max_length=10, required=False)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

src/company/forms.py
from django.forms import ModelForm
from .models import JobAdvertisement, InternshipAdvertisement


class JobAdvertisementForm(ModelForm):
    class Meta:
        model = JobAdvertisement
        exclude = ('id',)


class InternshipAdvertisementForm(ModelForm):
    class Meta:
        model = InternshipAdvertisement
        exclude = ('id', 'gross_salary',)

src/company/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, ListView, DetailView
from .forms import JobAdvertisementForm, InternshipAdvertisementForm
from company.models import JobAdvertisement, InternshipAdvertisement
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from accounts.models import CompanyProfile


class CompanyProfileRequiredMixin(LoginRequiredMixin):
    """Verify that the current user is authenticated."""

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'companyprofile'):
            return super().dispatch(request, *args, **kwargs)
        else:
            return self.handle_no_permission()


class JobAdvertisementFormView(CompanyProfileRequiredMixin, FormView):
    form_class = JobAdvertisementForm
    template_name = 'company/joboffer_form.html'
    success_url = '/company/job_offers/'

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.success_url)

    def post(self, request, *args, **kwargs):
        self.request.POST._mutable = True
        self.request.POST.update({
            'company': CompanyProfile.objects.get(user=self.request.user).id,
        })
        self.request.POST._mutable = False
        return super().post(request, args, kwargs)


class InternshipAdvertisementFormView(CompanyProfileRequiredMixin, FormView):
    form_class = InternshipAdvertisementForm
    template_name = 'company/internoffer_form.html'
    success_url = '/company/intern_offers/'

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.success_url)

    def post(self, request, *args, **kwargs):
        self.request.POST._mutable = True
        self.request.POST.update({
            'company': CompanyProfile.objects.get(user=self.request.user).id,
        })
        self.request.POST._mutable = False
        return super().post(request, args, kwargs)


class JobAdvertisementsAddedListView(CompanyProfileRequiredMixin, ListView):
    model = JobAdvertisement
    template_name = 'company/offers_list.html'
    context_object_name = 'ad_list'

    def get_queryset(self):
        return self.model.objects.filter(company__user=self.request.user)


class InternshipAdvertisementAddedListView(ListView):
    model = InternshipAdvertisement
    template_name = 'company/offers_list.html'
    context_object_name = 'ad_list'

    def get_queryset(self):
        return self.model.objects.filter(company__user=self.request.user)


class InternshipOfferView(LoginRequiredMixin, DetailView):
    model = InternshipAdvertisement
    template_name = 'company/offer.html'
    context_object_name = 'ad'

    def get_object(self, queryset=None):
        return get_object_or_404(InternshipAdvertisement, id=self.kwargs.get('id'))

    def get_context_data(self, **kwargs):
        context = super(InternshipOfferView, self).get_context_data(**kwargs)
        if hasattr(self.request.user, 'companyprofile'):
            context['base_template'] = 'company/base.html'

        elif hasattr(self.request.user, 'studentprofile'):
            context['base_template'] = 'student/base.html'
        context['type'] = "Internship"
        return context


class JobOfferView(LoginRequiredMixin, DetailView):
    model = JobAdvertisement
    template_name = 'company/offer.html'
    context_object_name = 'ad'

    def get_object(self, queryset=None):
        return get_object_or_404(JobAdvertisement, id=self.kwargs.get('id'))

    def get_context_data(self, **kwargs):
        context = super(JobOfferView, self).get_context_data(**kwargs)
        if hasattr(self.request.user, 'companyprofile'):
            context['base_template'] = 'company/base.html'

        elif hasattr(self.request.user, 'studentprofile'):
            context['base_template'] = 'student/base.html'
        context['type'] = "Job"
        return context

templates/company/register.html
{% extends 'main/base.html' %}
{% block body %}
<div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-10">
        <div class="card">
            <div class="my-card" id="my-card"><span style="font-size: 1.5rem"> &nbsp; Company Registration</span></div>
            <div class="card-block">
                <form method="post">
                    <div class="red-text">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                        {% endfor %}
                    </div>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-9">
                            <br>
                            <div class="md-form">
                                <i class="fa fa-user prefix" style="color: cornflowerblue"></i>
                                <label for="id_username" style="font-size: medium">Username:</label>
                                <input type="email" name="username" class="form-control" maxlength="254" required
                                       id="id_username"
                                       placeholder="Enter E-mail ID. This Email ID will be your username"/>
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-key prefix" style="color: cornflowerblue"></i>
                                <label for="id_password1" style="font-size: medium">Password:</label>
                                <input type="password" name="password1" class="form-control" required
                                       id="id_password1"/>

                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-key prefix" style="color: cornflowerblue"></i>
                                <label for="id_password2" style="font-size: medium">Password confirmation:</label>
                                <input type="password" name="password2" class="form-control" required
                                       id="id_password2"/>
                                <p>
                                <ul>
                                    <li style="font-size: small">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your
                                        password can&#39;t be too similar to your other personal information.
                                    </li>
                                    <li style="font-size: small">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your
                                        password must contain at least 8 characters.
                                    </li>
                                    <li style="font-size: small">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your
                                        password can&#39;t be a commonly used password.
                                    </li>
                                    <li style="font-size: small">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your
                                        password can&#39;t be entirely numeric.
                                    </li>
                                </ul>
                                </p>
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-user prefix" style="color: cornflowerblue"></i>
                                <label for="id_name">Name:</label>
                                <input type="text" name="name" maxlength="50" required id="id_name"
                                       placeholder="Name of the Company"/>
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-pencil prefix" style="color: cornflowerblue"></i>
                                <label for="id_domain">Domain:</label>
                                <input type="text" name="domain" maxlength="15" id="id_domain"
                                       placeholder="Type of company like banking/consulting etc"/>
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-globe prefix" style="color: cornflowerblue"></i>
                                <label for="id_url">Company URL:</label>
                                <input type="text" name="url"  id="id_url" placeholder="URL to company website">
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-map-marker prefix" style="color: cornflowerblue"></i>
                                <label for="id_city">City:</label>
                                <input type="text" name="city" maxlength="15" id="id_city"/>
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-map-marker prefix" style="color: cornflowerblue"></i>
                                <label for="id_state">State:</label>
                                <input type="text" name="state" maxlength="15" id="id_state"/>
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-map-marker prefix" style="color: cornflowerblue"></i>
                                <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Country: {{ form.country }}</span>
                            </div>
                            <br>
                            <div class="md-form">
                                <i class="fa fa-map-marker prefix" style="color: cornflowerblue"></i>
                                <label for="id_pin_code">Pin code:</label>
                                <input type="text" name="pin_code" maxlength="10" id="id_pin_code"/>
                            </div>


                            <button class="btn btn-primary" style="align: center" type="submit">Register</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-1"></div>

    </div>
</div>
{% endblock %}